[target.mipsel-unknown-linux-uclibc]
runner = "cargo exec runner"
linker = "/home/dmj/mipsel-linux-uclibc/bin/mipsel-linux-uclibc-cc"

[profile.release]
lto = true
opt-level = 'z'
codegen-units = 1


