[build]
target = "mipsel-unknown-linux-uclibc"

[target.mipsel-unknown-linux-uclibc]
runner = "cargo exec runner"
linker = "/home/dmj/mipsel-linux-uclibc/bin/mipsel-linux-uclibc-cc"

[profile.release]
lto = true #优化体积
opt-level = 'z'  # Optimize for size.
codegen-units = 1


